# Generated by Django 5.2.16 on 2026-07-15 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_alter_guest_options'),
        ('main', '0001_initial'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guest.guest'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='room.room'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('check_in_date__lt', models.F('check_out_date'))), name='reservation_check_in_before_check_out'),
        ),
    ]
