# Generated by Django 5.2.16 on 2026-07-15 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_reservation_status_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminoperationlog',
            name='action',
            field=models.CharField(choices=[('reservation_created', '创建订单'), ('reservation_updated', '修改订单'), ('reservation_confirmed', '确认订单'), ('reservation_cancelled', '取消订单'), ('reservation_checked_in', '办理入住'), ('reservation_checked_out', '办理退房'), ('reservation_no_show', '标记未到店'), ('room_created', '创建房间'), ('room_updated', '修改房间'), ('guest_created', '创建客人'), ('guest_updated', '修改客人'), ('reservation_note_created', '创建订单备注'), ('reservation_note_updated', '修改订单备注'), ('reservation_note_deleted', '删除订单备注'), ('reservation_note_importance_changed', '修改订单备注重要标记')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='adminoperationlog',
            name='target_type',
            field=models.CharField(choices=[('reservation', '订单'), ('room', '房间'), ('guest', '客人'), ('reservation_note', '订单备注')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='ReservationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=5000)),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_notes', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.reservation')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['reservation', 'created_at'], name='main_note_res_created_idx')],
            },
        ),
    ]
