# Generated by Django 5.2.16 on 2026-07-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'permissions': [('view_guest_sensitive_data', 'Can view masked guest government identification')]},
        ),
    ]
